activities_data = [
    {
        "name": "Royal Botanic Gardens",
        "category": "Parks and Gardens",
        "duration_hours": 2,
        "budget": "Basic",
    },
    {
        "name": "Brighton Beach",
        "category": "Beaches and Surf Spots",
        "duration_hours": 3,
        "budget": "Moderate",
    },
    {
        "name": "National Gallery of Victoria",
        "category": "Museums and Art",
        "duration_hours": 2,
        "budget": "Basic",
    },
    {
        "name": "Yarra Valley Wine Tour",
        "category": "Food, Vineyards, and Dining",
        "duration_hours": 5,
        "budget": "Premium",
    },
    {
        "name": "Luna Park",
        "category": "Family-Friendly",
        "duration_hours": 3,
        "budget": "Moderate",
    },
    {
        "name": "Queen Victoria Market",
        "category": "Shopping and Markets",
        "duration_hours": 2,
        "budget": "Basic",
    },
    {
        "name": "Melbourne Zoo",
        "category": "Family-Friendly",
        "duration_hours": 4,
        "budget": "Moderate",
    },
    {
        "name": "St Kilda Beach",
        "category": "Beaches and Surf Spots",
        "duration_hours": 3,
        "budget": "Basic",
    },
    {
        "name": "Melbourne Aquarium",
        "category": "Family-Friendly",
        "duration_hours": 3,
        "budget": "Moderate",
    },
    {
        "name": "Shrine of Remembrance",
        "category": "Historical Sites",
        "duration_hours": 1,
        "budget": "Basic",
    },
    {
        "name": "Fitzroy Gardens",
        "category": "Parks and Gardens",
        "duration_hours": 2,
        "budget": "Basic",
    },
    {
        "name": "Eureka Skydeck",
        "category": "Sightseeing",
        "duration_hours": 1,
        "budget": "Moderate",
    },
    {
        "name": "ACMI Museum",
        "category": "Museums and Art",
        "duration_hours": 2,
        "budget": "Basic",
    },
    {
        "name": "Dandenong Ranges",
        "category": "Nature and Scenic Spots",
        "duration_hours": 6,
        "budget": "Moderate",
    },
    {
        "name": "Phillip Island Penguin Parade",
        "category": "Family-Friendly",
        "duration_hours": 4,
        "budget": "Premium",
    },
    {
        "name": "Federation Square",
        "category": "Sightseeing",
        "duration_hours": 1,
        "budget": "Basic",
    },
    {
        "name": "Melbourne Cricket Ground Tour",
        "category": "Sports",
        "duration_hours": 2,
        "budget": "Moderate",
    },
    {
        "name": "Healesville Sanctuary",
        "category": "Family-Friendly",
        "duration_hours": 5,
        "budget": "Premium",
    },
    {
        "name": "Royal Arcade Shopping",
        "category": "Shopping and Markets",
        "duration_hours": 2,
        "budget": "Moderate",
    },
    {
        "name": "Mornington Peninsula Hot Springs",
        "category": "Wellness and Relaxation",
        "duration_hours": 4,
        "budget": "Premium",
    },
    {
        "name": "Crown Casino",
        "category": "Pubs and Bars",
        "duration_hours": 3,
        "budget": "Premium",
    },
    {
        "name": "Puffing Billy Railway",
        "category": "Family-Friendly",
        "duration_hours": 3,
        "budget": "Moderate",
    },
    {
        "name": "Hosier Lane Street Art",
        "category": "Museums and Art",
        "duration_hours": 1,
        "budget": "Basic",
    },
    {
        "name": "Melbourne Museum",
        "category": "Museums and Art",
        "duration_hours": 3,
        "budget": "Moderate",
    },
    {
        "name": "Albert Park Lake",
        "category": "Parks and Gardens",
        "duration_hours": 2,
        "budget": "Basic",
    },
    {
        "name": "Werribee Open Range Zoo",
        "category": "Family-Friendly",
        "duration_hours": 5,
        "budget": "Premium",
    },
    {
        "name": "Old Melbourne Gaol",
        "category": "Historical Sites",
        "duration_hours": 2,
        "budget": "Moderate",
    },
    {
        "name": "Block Arcade Shopping",
        "category": "Shopping and Markets",
        "duration_hours": 1,
        "budget": "Moderate",
    },
    {
        "name": "Scienceworks",
        "category": "Museums and Art",
        "duration_hours": 3,
        "budget": "Basic",
    },
    {
        "name": "Hanging Rock",
        "category": "Nature and Scenic Spots",
        "duration_hours": 4,
        "budget": "Moderate",
    },
    {
        "name": "Chinatown Melbourne",
        "category": "Food, Vineyards, and Dining",
        "duration_hours": 2,
        "budget": "Basic",
    },
    {
        "name": "Port Melbourne Beach",
        "category": "Beaches and Surf Spots",
        "duration_hours": 2,
        "budget": "Basic",
    },
    {
        "name": "Arts Centre Melbourne",
        "category": "Museums and Art",
        "duration_hours": 2,
        "budget": "Moderate",
    },
    {
        "name": "Carlton Gardens",
        "category": "Parks and Gardens",
        "duration_hours": 2,
        "budget": "Basic",
    },
    {
        "name": "Collingwood Children's Farm",
        "category": "Family-Friendly",
        "duration_hours": 3,
        "budget": "Basic",
    },
    {
        "name": "St Paul's Cathedral",
        "category": "Historical Sites",
        "duration_hours": 1,
        "budget": "Basic",
    },
    {
        "name": "Flinders Street Station Tour",
        "category": "Historical Sites",
        "duration_hours": 1,
        "budget": "Basic",
    },
    {
        "name": "King and Godfree Rooftop Bar",
        "category": "Pubs and Bars",
        "duration_hours": 2,
        "budget": "Moderate",
    },
    {
        "name": "South Melbourne Market",
        "category": "Shopping and Markets",
        "duration_hours": 2,
        "budget": "Basic",
    },
    {
        "name": "Polly Woodside Tall Ship",
        "category": "Historical Sites",
        "duration_hours": 1,
        "budget": "Basic",
    },
    {
        "name": "Yarra River Cruise",
        "category": "Nature and Scenic Spots",
        "duration_hours": 2,
        "budget": "Moderate",
    },
    {
        "name": "Kilda Adventure Playground",
        "category": "Family-Friendly",
        "duration_hours": 2,
        "budget": "Basic",
    },
    {
        "name": "The Australian Ballet",
        "category": "Museums and Art",
        "duration_hours": 3,
        "budget": "Premium",
    },
    {
        "name": "Prahran Market",
        "category": "Shopping and Markets",
        "duration_hours": 2,
        "budget": "Basic",
    },
    {
        "name": "Pentridge Prison Tour",
        "category": "Historical Sites",
        "duration_hours": 2,
        "budget": "Moderate",
    },
    {
        "name": "Skydiving over St Kilda",
        "category": "Sports",
        "duration_hours": 4,
        "budget": "Premium",
    },
    {
        "name": "Melbourne Jazz Club",
        "category": "Pubs and Bars",
        "duration_hours": 3,
        "budget": "Moderate",
    },
    {
        "name": "NGV Friday Nights",
        "category": "Museums and Art",
        "duration_hours": 2,
        "budget": "Moderate",
    },
    {
        "name": "Koorie Heritage Trust",
        "category": "Museums and Art",
        "duration_hours": 2,
        "budget": "Basic",
    },
    {
        "name": "Victoria Street Food Tour",
        "category": "Food, Vineyards, and Dining",
        "duration_hours": 3,
        "budget": "Moderate",
    },
    {
        "name": "Melbourne Star Observation Wheel",
        "category": "Sightseeing",
        "duration_hours": 1,
        "budget": "Moderate",
    },
    {
        "name": "William Ricketts Sanctuary",
        "category": "Nature and Scenic Spots",
        "duration_hours": 3,
        "budget": "Basic",
    },
    {
        "name": "Escape Room",
        "category": "Sports",
        "duration_hours": 2,
        "budget": "Moderate",
    },
    {
        "name": "Queen Street Cafe",
        "category": "Cafes",
        "duration_hours": 1,
        "budget": "Basic",
    },
    {
        "name": "South Melbourne Night Market",
        "category": "Markets",
        "duration_hours": 3,
        "budget": "Moderate",
    },
    {
        "name": "The Hardware Société",
        "category": "Cafes",
        "duration_hours": 1.5,
        "budget": "Moderate",
    },
    {
        "name": "Prahran Market Food Tour",
        "category": "Markets",
        "duration_hours": 2,
        "budget": "Moderate",
    },
    {
        "name": "Degraves Espresso Bar",
        "category": "Cafes",
        "duration_hours": 1,
        "budget": "Basic",
    },
    {
        "name": "The Rose Street Artists' Market",
        "category": "Markets",
        "duration_hours": 2,
        "budget": "Basic",
    },
    {
        "name": "Market Lane Coffee",
        "category": "Cafes",
        "duration_hours": 1,
        "budget": "Basic",
    },
    {
        "name": "Camberwell Sunday Market",
        "category": "Markets",
        "duration_hours": 3,
        "budget": "Basic",
    },
    {
        "name": "Pellegrini’s Espresso Bar",
        "category": "Cafes",
        "duration_hours": 1,
        "budget": "Basic",
    },
    {
        "name": "Dandenong Market",
        "category": "Markets",
        "duration_hours": 3,
        "budget": "Basic",
    },
    {
        "name": "Auction Rooms Cafe",
        "category": "Cafes",
        "duration_hours": 1.5,
        "budget": "Moderate",
    },
    {
        "name": "Bentleigh Farmers' Market",
        "category": "Markets",
        "duration_hours": 2,
        "budget": "Basic",
    },
    {
        "name": "Brother Baba Budan",
        "category": "Cafes",
        "duration_hours": 1,
        "budget": "Basic",
    },
    {
        "name": "Melbourne Farmers' Market",
        "category": "Markets",
        "duration_hours": 3,
        "budget": "Moderate",
    },
    {
        "name": "Brunetti Cafe Carlton",
        "category": "Cafes",
        "duration_hours": 1.5,
        "budget": "Moderate",
    },
    {
        "name": "Docklands Sunday Market",
        "category": "Markets",
        "duration_hours": 2,
        "budget": "Basic",
    },
    {
        "name": "Wide Open Road Cafe",
        "category": "Cafes",
        "duration_hours": 1.5,
        "budget": "Basic",
    },
    {
        "name": "Abbotsford Convent Market",
        "category": "Markets",
        "duration_hours": 3,
        "budget": "Moderate",
    },
    {
        "name": "Patricia Coffee Brewers",
        "category": "Cafes",
        "duration_hours": 1,
        "budget": "Basic",
    },
    {
        "name": "Hawthorn Makers Market",
        "category": "Markets",
        "duration_hours": 3,
        "budget": "Basic",
    },
    {
        "name": "Aunty Peg's Coffee",
        "category": "Cafes",
        "duration_hours": 1,
        "budget": "Moderate",
    },
    {
        "name": "Caribbean Gardens Market",
        "category": "Markets",
        "duration_hours": 3,
        "budget": "Moderate",
    },
    {
        "name": "Higher Ground Cafe",
        "category": "Cafes",
        "duration_hours": 2,
        "budget": "Premium",
    },
    {
        "name": "Mornington Main Street Market",
        "category": "Markets",
        "duration_hours": 3,
        "budget": "Basic",
    },
    {
        "name": "Proud Mary Coffee",
        "category": "Cafes",
        "duration_hours": 1.5,
        "budget": "Moderate",
    },
    {
        "name": "Farmers Market at the University of Melbourne",
        "category": "Markets",
        "duration_hours": 2,
        "budget": "Basic",
    },
    {
        "name": "Krimper Cafe",
        "category": "Cafes",
        "duration_hours": 1.5,
        "budget": "Moderate",
    },
    {
        "name": "Yarraville Pop-Up Market",
        "category": "Markets",
        "duration_hours": 3,
        "budget": "Basic",
    },
    {
        "name": "Industry Beans Fitzroy",
        "category": "Cafes",
        "duration_hours": 1.5,
        "budget": "Premium",
    },
    {
        "name": "St Andrews Market",
        "category": "Markets",
        "duration_hours": 3,
        "budget": "Basic",
    },
]
